change test command

diff --git a/.github/deploy.yml b/.github/deploy.yml
--- a/.github/deploy.yml
+++ b/.github/deploy.yml
@@ -27,28 +27,29 @@ jobs:
     needs: deploy
     if: ${{ needs.changes.outputs.frontend == 'true' }}
     runs-on: ubuntu-latest
-    defaults:
-      run:
-        # Frontend folder working directory.
-        working-directory: smtalent-react-ecommerce
+
     steps:
-      - name: Checkout code
+      - name: 🚚 Get latest code
       - uses: actions/checkout@v4
+
+      - name: 📂 Set working directory
+        run: cd smtalent-react-ecommerce
+
       - name: Configure AWS credentials using OIDC
         uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_OIDC_ID }}
           aws-region: ${{ secrets.AWS_REGION }}
 
-      - name: Execute commands via SSM
+      - name: Execute commands via SSM #, "runuser -l ubuntu git pull origin staging", "sudo systemctl restart gunicorn.service && echo Gunicorn restarted successfully || echo Gunicorn failed to restart"
         id: execute_command
         run: |
           COMMAND_ID=$(aws ssm send-command \
             --instance-ids ${{ secrets.AWS_INSTANCE_ID }} \
             --document-name "AWS-RunShellScript" \
-            --parameters 'commands=["echo "Commands to be executed" ",
-                                    "whoami"]' \
-            --comment "Deploying comment" \
+            --parameters 'commands=["echo "Commands to be executed" ", 
+              "whoami"]' \
+            --comment "Deploying To Staging"" \
             --query "Command.CommandId" \
             --output text)
 
